### ISSUE TITLE
Server: Block suspiciously large number of connections from one client

### ISSUE THREAD

**Issue by andreaulicna** [loudapet/42webserv#2]
- getpeername to get the IP of the client
- if the same IP is on different sockets, reject connection (DDoS attack)

**Comment by loudapet** [comment]
`getpeername()` is disallowed, we need to use `accept()` info instead

**Comment by loudapet** [comment]
Subject says nothing about this, would be too risky because we might start refusing connections even when we're not supposed to (e.g. during siege -b)
