### ISSUE TITLE
Allow duplicate ports in server default

### ISSUE THREAD

**Issue by andreaulicna** [loudapet/42webserv#32]
- Rewritte selectServerRules to handle duplicate ports:
  - search for default_server that matches port, IP address and server_name
  - search for server that matches port, IP address and server_name
  - search for first server that matches port and IP address (NGINX allows this, we don't want to)
- Edit server config parser to allow duplicate ports
- Include wildcard Server Names?
```
bool	isValidWildcardName(std::vector<std::string> &serverNames)
{
	for (size_t i = 0; i < serverNames.size(); i++)
	{
		if (serverNames[i].find("*") != std::string::npos)
		{
			if (serverNames[i][0] != '*' && serverNames[i][serverNames[i].length() - 1] != '*')
				return (false);
			else
				if (serverNames[i][1] != '.' && serverNames[i][serverNames[i].length() - 2] != '.')
					return (false);
		}
	}
	return (true);
}

if (!isValidWildcardName(this->_serverNames))
	throw (std::runtime_error("Config parser: Invalid server name (wildcard)."));
```

**Comment by loudapet** [comment]
Eval sheet mentions this should not work, therefore it doesn't work.
