### ISSUE TITLE
Process alll data in _receivedData (unless more is needed) before going through select again

### ISSUE THREAD

**Issue by andreaulicna** [loudapet/42webserv#41]
while loop in ServerMaster

**Comment by andreaulicna** [comment]
Note renaming:
  - `_dataToParse` to `_receivedData`
  - `_findValidHeaderEnd()` to` _separateValidHeader()` (and added `hasValidHeaderEnd()` checker function)

### **CHANGES**
- Added while loop into the try-catch block in ServerMaster that wraps around the whole try part
- The while loop condition checks the size of `_receivedData` (buffer) to process everything (unless it's a request with incomplete header)
- If it's a request with an incomplete header (no valid sequence found), the 1st if statement breaks the while loop so that we go through select again and get the rest of the header
- The rest of the ifs stayed fundamentally the same, just relatively small changes were made:
  - The condition in the if handling the first iteration of the while loop now doesn't have the `findValidHeaderEnd()` function as the separation of the header and the body that we have in the buffer is done by a `void separateValidHeader()` function that is called when the if evaluates to true
  - Once the request processing is completed (`requestComplete` == true), we need to reset the values in the request object to the initial values before processing a new request
    - `resetRequestObject()` does that when everything goes okay (not when an exception is thrown, though - see NEXT)


### **NEXT**
- Reset the values of the `request `object saved in the Client (or at least the `readingBodyInProgress` and `requestComplete` flags) whenever an exception is thrown from HttpParser
  - it's because the if handling the first iteration of the while loop wasn't evaluating to true and getting executed for chained requests (`requestComplete` was set to true)
  - there is a dirty fix in `readRequestBody()` for one of the exceptions - it was getting thrown when the mainClient was run to connect to the server
 ![Image](https://github.com/loudapet/42webserv/assets/106449030/6b41f106-aaf9-4ef1-b1ea-dd6e45b3a2e6)
- Include support for content length (the current version works only for transfer encoding)
- Rewrite into a do-while loop (to potentially get rid of the if with break) - @okraus42💡

**Comment by loudapet** [comment]
@andreaulicna this is basically done now, right?

**Comment by andreaulicna** [comment]
Yesss, everything left (or I thought that was left 😅) was fixed when we spoke about it on campus.
