### ISSUE TITLE
Log file directives in config

### ISSUE THREAD

**Issue by andreaulicna** [loudapet/42webserv#81]
<del>
Logs directive:
- if `logs` directive `on`, but the file doesn't exist -> invalid config
- in server scope

Logs_file:
- not mandatory -> console default
- if given, but file doesn't exists -> invalid config
- check if file exits and write (read not needed) persmissions -> can be anywhere, same as mime types

Logs_level:
- not mandatory -> all default
- options: debug, info, notice, warning, error

```
logs       on;
logs_file  logger_logs;
logs_level LEVEL;
```
</del>

<br>

`logs_file` ✔️ `logs_level` ✔️ -> logs in the log file with no colours based on the level
`logs_file` ✔️ `logs_level` ❌ -> set level to INFO
`logs_file` ❌ `logs_level` ✔️ -> logs in the console based on the specified level
`logs_file` ❌ `logs_level` ❌ -> logs in the console based on the default level (= info)

```
logs_file  logs.txt;
logs_level [LEVEL];
```

**Comment by loudapet** [comment]
minor correction: if logs_level is not specified, let's make `info` the default, and not `debug`, because `debug` floods the logs with mostly unnecessary data
